env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: ghtool
    main: ./cmd/ghtool
    binary: ghtool
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - allow_different_binary_count: true

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: ghtool
    package_name: ghtool
    file_name_template: "ghtool_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    builds:
      - ghtool
    homepage: https://github.com/na4ma4/ghtool
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: GitHub API Tool
    formats:
      - apk
      - deb
    bindir: /usr/sbin

brews:
  -
    name: ghtool
    tap:
      owner: na4ma4
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: na4ma4@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/na4ma4/ghtool
    description: GitHub API Tool
    test: |
      system "#{bin}/ghtool --version"
    install: |
      bin.install "ghtool"
